#!/bin/sh

# Modify the sml invocation below appropriately for your system.

# For Linux:
. ../config_env.shrc
sml @SMLload=./.heap/pml.x86-linux

# For Cygwin:
#"C:/Program Files/SMLNJ/bin/sml.bat" @SMLload="C:\\home\\gb\\Teaching\\csc7101\\Sp10\\Labs\\Prolog\\.heap\\pml.x86-win32"
